# Site settings
title: The Quick Quotes Quill 
email: cassidy2@vt.edu
description: > # this means to ignore newlines until "baseurl:"
  Inspired by Rita Skeeter's Quick Quotes Quill (but not bewitched 
  	with the same embellishment charm) -- A blog about a young software developer and her dog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://http.cassidyheath.github.io/ # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
github_username:  cassidyheath

# Build settings
markdown: kramdown